# Generated by Django 2.2.5 on 2020-02-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/cars_pictures')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('SED', 'Sedan'), ('SUV', 'SUV'), ('CON', 'Convertible'), ('MIN', 'Minivan'), ('HAT', 'Hatchback'), ('CRE', 'Crew Cab'), ('COU', 'Coupe'), ('REG', 'Regular Cab'), ('VAN', 'Van'), ('WAG', 'Wagon')], max_length=3)),
                ('brand', models.CharField(max_length=100)),
                ('num_of_passengers', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('air_conditioning', models.BooleanField()),
                ('automatic_transmission', models.BooleanField()),
                ('doors_4', models.BooleanField()),
            ],
        ),
    ]
