# Generated by Django 2.2.5 on 2020-02-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cars_pictures'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan'), ('Hatchback', 'Hatchback'), ('Crew Cab', 'Crew Cab'), ('Coupe', 'Coupe'), ('Regular Cab', 'Regular Cab'), ('Van', 'Van'), ('Wagon', 'Wagon')], max_length=3),
        ),
    ]
